import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          마, <a href="https://nextjs.org">반갑다!</a>
        </h1>
        <h2 className={styles.title}>
          곧 <a href="https://nextjs.org">수정</a> 할거니까 조금만 기다려.
        </h2>
      </main>
    </div>
  );
};
export default Home;
